### ISSUE TITLE
expo47 on verge of deprecation

### ISSUE THREAD

**Issue by ReedNathan001** [kev0051/DustblockBlues#7]
Will look into upgrading to 48,49, and breaking changes

**Comment by ReedNathan001** [comment]
![Screen Shot 2023-10-28 at 4 46 34 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/863477de-4fca-42a1-ab5c-8ef6fa2cbdaa)
![Screen Shot 2023-10-28 at 4 47 03 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/e2fc8b89-ccba-4b35-b881-37710d7e6b5f)
![Screen Shot 2023-10-28 at 4 47 24 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/0d95cb01-41d1-47f8-81fb-640a395fc09b)
![Screen Shot 2023-10-28 at 4 47 56 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/95df473e-ba53-482a-9912-063fa9d3d381)
![Screen Shot 2023-10-28 at 4 48 21 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/80101336-6c0c-46a7-a6f5-93d4753e39b5)
![Screen Shot 2023-10-28 at 4 48 40 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/8ce89d4b-2c96-4724-9c96-5e09ee80bba3)
![Screen Shot 2023-10-28 at 4 49 04 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/2f42ac8c-d73a-49ef-88a3-996173a8be59)
![Screen Shot 2023-10-28 at 4 49 24 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/9666b023-e5ef-4155-8f4b-a6f1a68acc48)

**Comment by ReedNathan001** [comment]
locate functions. but identify doesn't. live mode freezes app. taking photo gives: 
Argument 'x' passed to 'cast' must be a Tensor or TensorLike, but got 'Tensor'
at node_modules/@tensorflow/tfjs/dist/tf.node.js:3794:23 in convertToTensor
at node_modules/@tensorflow/tfjs/dist/tf.node.js:3903:30 in cast_
at node_modules/@tensorflow/tfjs/dist/tf.node.js:3857:29 in f2
at node_modules/@tensorflow/tfjs/dist/tf.node.js:30387:15 in getGlobalTensorClass.prototype.cast
at Navigation/Screens/CameraScreen.jsx:207:35 in handleImageCapture
at Navigation/Screens/CameraScreen.jsx:200:28 in CameraScreen
at Navigation/Screens/CameraScreen.jsx:334:49 in Pressable.props.onPress
at node_modules/react-native/Libraries/Pressability/Pressability.js:758:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:695:40 in _receiveSignal
- ... 21 more stack frames from framework internals

**Comment by ReedNathan001** [comment]
![Screen Shot 2023-10-28 at 5 16 21 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/60ba9176-6fbf-4793-8729-58889049d013)
in app.json
{
  'expo': {
    ...
      'jsEngine': 'jsc'
    ...
  }
}
https://stackoverflow.com/questions/74139366/argument-x-passed-to-cast-must-be-a-tensor-or-tensorlike-but-got-tensor-f

**Comment by ReedNathan001** [comment]
![Screen Shot 2023-10-28 at 5 19 55 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/2d575f5b-50d6-4826-b00b-3c99bdb22da3)

**Comment by ReedNathan001** [comment]
![Screen Shot 2023-10-28 at 5 23 10 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/3afd2bf3-3e58-40ce-a7fa-57d0b0ac6607)
![Screen Shot 2023-10-28 at 5 23 16 PM](https://github.com/kev0051/DustblockBlues/assets/92693641/cbfaed94-4934-4361-9834-30b61b0a527d)
old ghosts

**Comment by ReedNathan001** [comment]
![IMG_9632](https://github.com/kev0051/DustblockBlues/assets/92693641/0424753d-b8a6-45e0-8d3a-55f9290440b2)
![IMG_9631](https://github.com/kev0051/DustblockBlues/assets/92693641/225aa34e-fbcf-45b4-be9d-028fdcdb77c2)
![IMG_9630](https://github.com/kev0051/DustblockBlues/assets/92693641/9047cd71-8878-4a05-b08c-b20ae02cf703)
![IMG_9629](https://github.com/kev0051/DustblockBlues/assets/92693641/0caf1a22-8ac2-4b78-9feb-310fb6228079)
![IMG_9628](https://github.com/kev0051/DustblockBlues/assets/92693641/aa823b29-81dd-4089-ad58-634e64a4b1f3)
![IMG_9627](https://github.com/kev0051/DustblockBlues/assets/92693641/4213f7d2-1aa1-43c6-98f6-87a7047aaabd)
![IMG_9625](https://github.com/kev0051/DustblockBlues/assets/92693641/1a8c457e-d1ec-4023-b098-7789de4afae9)
pardon the junk. proof it works on expo48, albeit with random accuracy

**Comment by ReedNathan001** [comment]
will now try to upgrade to expo49
